package main

const (
	ADD_ACTIVITY         = "INSERT"
	UPDATE_ACTIVITY      = "UPDATE"
	DELETE_ACTIVITY      = "DELETE"
	RESET_PASS_ACTIVITY  = "RESET-PASS"
	CHANGE_PASS_ACTIVITY = "CHANGE-PASS"
	LOGIN_ACTIVITY       = "LOGIN"
	LOGOUT_ACTIVITY      = "LOGOUT"
	FORGET_PASS          = "FORGET-PASS"
)
